name: Tag release and publish to Nexus

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: arc-runner-set
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
      - name: Parse tag to ENV
        run: |
          echo RELEASE_TAG=$(poetry version --short) >> ${GITHUB_ENV}
          cat ${GITHUB_ENV}
      - uses: rickstaa/action-create-tag@v1
        if: ${{ !env.ACT }}
        id: "tag_create"
        with:
          tag: ${{ env.RELEASE_TAG }}
          tag_exists_error: false

  publish:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry twine
      - name: build dist
        run: |
          poetry build -f sdist
          poetry build -f wheel
      - name: Upload
        if: ${{ !env.ACT }}
        env:
          TWINE_REPOSITORY_URL: https://nexus.dev.pvarki.fi/repository/pypilocal/
          TWINE_USERNAME: nexusbot
          TWINE_PASSWORD: ${{ secrets.NEXUSBOT_PAT }}
          TWINE_NON_INTERACTIVE: 1
        run: |
          twine upload dist/*
